// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	repository2 "github.com/zmsocc/practice/webook/interactive/repository"
	cache2 "github.com/zmsocc/practice/webook/interactive/repository/cache"
	dao2 "github.com/zmsocc/practice/webook/interactive/repository/dao"
	service2 "github.com/zmsocc/practice/webook/interactive/service"
	"github.com/zmsocc/practice/webook/internal/event/article"
	"github.com/zmsocc/practice/webook/internal/repository"
	articles2 "github.com/zmsocc/practice/webook/internal/repository/articles"
	"github.com/zmsocc/practice/webook/internal/repository/cache"
	"github.com/zmsocc/practice/webook/internal/repository/dao"
	"github.com/zmsocc/practice/webook/internal/repository/dao/articles"
	"github.com/zmsocc/practice/webook/internal/service"
	"github.com/zmsocc/practice/webook/internal/web"
	"github.com/zmsocc/practice/webook/internal/web/ijwt"
	"github.com/zmsocc/practice/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	handler := ijwt.NewRedisJWTHandler(cmdable)
	v := ioc.InitMiddlewares(handler, cmdable)
	gormDB := InitTestDB()
	userDAO := dao.NewUserDAO(gormDB)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSMSService(cmdable)
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, handler, codeService)
	articleDAO := articles.NewArticleDao(gormDB)
	articleCache := cache.NewArticleCache(cmdable)
	logger := InitLog()
	articleRepository := articles2.NewArticleRepository(articleDAO, articleCache, logger)
	client := InitKafka()
	syncProducer := NewSyncProducer(client)
	producer := article.NewKafkaProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, logger, producer)
	interactiveDAO := dao2.NewInteractiveDAO(gormDB)
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewInteractiveRepository(interactiveDAO, interactiveCache, logger)
	interactiveService := service2.NewInteractiveService(interactiveRepository, logger)
	articleHandler := web.NewArticleHandler(articleService, logger, interactiveService)
	engine := ioc.InitWebServer(v, userHandler, articleHandler)
	return engine
}

func InitArticleHandler(dao3 articles.ArticleDAO) *web.ArticleHandler {
	cmdable := InitRedis()
	articleCache := cache.NewArticleCache(cmdable)
	logger := InitLog()
	articleRepository := articles2.NewArticleRepository(dao3, articleCache, logger)
	client := InitKafka()
	syncProducer := NewSyncProducer(client)
	producer := article.NewKafkaProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, logger, producer)
	gormDB := InitTestDB()
	interactiveDAO := dao2.NewInteractiveDAO(gormDB)
	interactiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewInteractiveRepository(interactiveDAO, interactiveCache, logger)
	interactiveService := service2.NewInteractiveService(interactiveRepository, logger)
	articleHandler := web.NewArticleHandler(articleService, logger, interactiveService)
	return articleHandler
}

func InitUserSvc() service.UserService {
	gormDB := InitTestDB()
	userDAO := dao.NewUserDAO(gormDB)
	cmdable := InitRedis()
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	return userService
}

func InitJwtHdl() ijwt.Handler {
	cmdable := InitRedis()
	handler := ijwt.NewRedisJWTHandler(cmdable)
	return handler
}

// wire.go:

var thirdProvider = wire.NewSet(
	InitRedis,
	NewSyncProducer,
	InitKafka,
	InitTestDB, InitLog,
)

var userSvcProvider = wire.NewSet(dao.NewUserDAO, cache.NewUserCache, repository.NewUserRepository, service.NewUserService)

var interactiveSvcProvider = wire.NewSet(service2.NewInteractiveService, repository2.NewInteractiveRepository, dao2.NewInteractiveDAO, cache2.NewRedisInteractiveCache)

var articlSvcProvider = wire.NewSet(articles.NewArticleDao, cache.NewArticleCache, articles2.NewArticleRepository, service.NewArticleService)
